export enum Path {
  HOME = '/',
  USER = 'users/:id',
  USERS = 'users',
  CITY = 'cities/:id',
  CITIES = 'cities',
  GOOD = 'good/:id',
  GOODS = 'goods',
  STOCK = 'stocks/:id',
  STOCKS = 'stocks',
  REVIEW = 'reviews/:id',
  REVIEWS = 'reviews',
  CATEGORY = 'categories/:id',
  CATEGORIES = 'categories',
  PAGE = 'pages/:id',
  PAGES = 'pages',
  REGISTRATION = 'registrations-confirmations',
  AUTH = 'auth',
  ERROR_PAGE = '404',
}
